<?php
/**
 * Created by PhpStorm.
 */
class Country extends CI_Model {

    public $countryArray = array(
        'AD'=>array('name'=>'ANDORRA','code'=>'376'),
        'AE'=>array('name'=>'UNITED ARAB EMIRATES','code'=>'971'),
        'AF'=>array('name'=>'AFGHANISTAN','code'=>'93'),
        'AG'=>array('name'=>'ANTIGUA AND BARBUDA','code'=>'1268'),
        'AI'=>array('name'=>'ANGUILLA','code'=>'1264'),
        'AL'=>array('name'=>'ALBANIA','code'=>'355'),
        'AM'=>array('name'=>'ARMENIA','code'=>'374'),
        'AN'=>array('name'=>'NETHERLANDS ANTILLES','code'=>'599'),
        'AO'=>array('name'=>'ANGOLA','code'=>'244'),
        'AQ'=>array('name'=>'ANTARCTICA','code'=>'672'),
        'AR'=>array('name'=>'ARGENTINA','code'=>'54'),
        'AS'=>array('name'=>'AMERICAN SAMOA','code'=>'1684'),
        'AT'=>array('name'=>'AUSTRIA','code'=>'43'),
        'AU'=>array('name'=>'AUSTRALIA','code'=>'61'),
        'AW'=>array('name'=>'ARUBA','code'=>'297'),
        'AZ'=>array('name'=>'AZERBAIJAN','code'=>'994'),
        'BA'=>array('name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'),
        'BB'=>array('name'=>'BARBADOS','code'=>'1246'),
        'BD'=>array('name'=>'BANGLADESH','code'=>'880'),
        'BE'=>array('name'=>'BELGIUM','code'=>'32'),
        'BF'=>array('name'=>'BURKINA FASO','code'=>'226'),
        'BG'=>array('name'=>'BULGARIA','code'=>'359'),
        'BH'=>array('name'=>'BAHRAIN','code'=>'973'),
        'BI'=>array('name'=>'BURUNDI','code'=>'257'),
        'BJ'=>array('name'=>'BENIN','code'=>'229'),
        'BL'=>array('name'=>'SAINT BARTHELEMY','code'=>'590'),
        'BM'=>array('name'=>'BERMUDA','code'=>'1441'),
        'BN'=>array('name'=>'BRUNEI DARUSSALAM','code'=>'673'),
        'BO'=>array('name'=>'BOLIVIA','code'=>'591'),
        'BR'=>array('name'=>'BRAZIL','code'=>'55'),
        'BS'=>array('name'=>'BAHAMAS','code'=>'1242'),
        'BT'=>array('name'=>'BHUTAN','code'=>'975'),
        'BW'=>array('name'=>'BOTSWANA','code'=>'267'),
        'BY'=>array('name'=>'BELARUS','code'=>'375'),
        'BZ'=>array('name'=>'BELIZE','code'=>'501'),
        'CA'=>array('name'=>'CANADA','code'=>'1'),
        'CC'=>array('name'=>'COCOS (KEELING) ISLANDS','code'=>'61'),
        'CD'=>array('name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'243'),
        'CF'=>array('name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'),
        'CG'=>array('name'=>'CONGO','code'=>'242'),
        'CH'=>array('name'=>'SWITZERLAND','code'=>'41'),
        'CI'=>array('name'=>'COTE D IVOIRE','code'=>'225'),
        'CK'=>array('name'=>'COOK ISLANDS','code'=>'682'),
        'CL'=>array('name'=>'CHILE','code'=>'56'),
        'CM'=>array('name'=>'CAMEROON','code'=>'237'),
        'CN'=>array('name'=>'CHINA','code'=>'86'),
        'CO'=>array('name'=>'COLOMBIA','code'=>'57'),
        'CR'=>array('name'=>'COSTA RICA','code'=>'506'),
        'CU'=>array('name'=>'CUBA','code'=>'53'),
        'CV'=>array('name'=>'CAPE VERDE','code'=>'238'),
        'CX'=>array('name'=>'CHRISTMAS ISLAND','code'=>'61'),
        'CY'=>array('name'=>'CYPRUS','code'=>'357'),
        'CZ'=>array('name'=>'CZECH REPUBLIC','code'=>'420'),
        'DE'=>array('name'=>'GERMANY','code'=>'49'),
        'DJ'=>array('name'=>'DJIBOUTI','code'=>'253'),
        'DK'=>array('name'=>'DENMARK','code'=>'45'),
        'DM'=>array('name'=>'DOMINICA','code'=>'1767'),
        'DO'=>array('name'=>'DOMINICAN REPUBLIC','code'=>'1809'),
        'DZ'=>array('name'=>'ALGERIA','code'=>'213'),
        'EC'=>array('name'=>'ECUADOR','code'=>'593'),
        'EE'=>array('name'=>'ESTONIA','code'=>'372'),
        'EG'=>array('name'=>'EGYPT','code'=>'20'),
        'ER'=>array('name'=>'ERITREA','code'=>'291'),
        'ES'=>array('name'=>'SPAIN','code'=>'34'),
        'ET'=>array('name'=>'ETHIOPIA','code'=>'251'),
        'FI'=>array('name'=>'FINLAND','code'=>'358'),
        'FJ'=>array('name'=>'FIJI','code'=>'679'),
        'FK'=>array('name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'500'),
        'FM'=>array('name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'691'),
        'FO'=>array('name'=>'FAROE ISLANDS','code'=>'298'),
        'FR'=>array('name'=>'FRANCE','code'=>'33'),
        'GA'=>array('name'=>'GABON','code'=>'241'),
        'GB'=>array('name'=>'UNITED KINGDOM','code'=>'44'),
        'GD'=>array('name'=>'GRENADA','code'=>'1473'),
        'GE'=>array('name'=>'GEORGIA','code'=>'995'),
        'GH'=>array('name'=>'GHANA','code'=>'233'),
        'GI'=>array('name'=>'GIBRALTAR','code'=>'350'),
        'GL'=>array('name'=>'GREENLAND','code'=>'299'),
        'GM'=>array('name'=>'GAMBIA','code'=>'220'),
        'GN'=>array('name'=>'GUINEA','code'=>'224'),
        'GQ'=>array('name'=>'EQUATORIAL GUINEA','code'=>'240'),
        'GR'=>array('name'=>'GREECE','code'=>'30'),
        'GT'=>array('name'=>'GUATEMALA','code'=>'502'),
        'GU'=>array('name'=>'GUAM','code'=>'1671'),
        'GW'=>array('name'=>'GUINEA-BISSAU','code'=>'245'),
        'GY'=>array('name'=>'GUYANA','code'=>'592'),
        'HK'=>array('name'=>'HONG KONG','code'=>'852'),
        'HN'=>array('name'=>'HONDURAS','code'=>'504'),
        'HR'=>array('name'=>'CROATIA','code'=>'385'),
        'HT'=>array('name'=>'HAITI','code'=>'509'),
        'HU'=>array('name'=>'HUNGARY','code'=>'36'),
        'ID'=>array('name'=>'INDONESIA','code'=>'62'),
        'IE'=>array('name'=>'IRELAND','code'=>'353'),
        'IL'=>array('name'=>'ISRAEL','code'=>'972'),
        'IM'=>array('name'=>'ISLE OF MAN','code'=>'44'),
        'IN'=>array('name'=>'INDIA','code'=>'91'),
        'IQ'=>array('name'=>'IRAQ','code'=>'964'),
        'IR'=>array('name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'98'),
        'IS'=>array('name'=>'ICELAND','code'=>'354'),
        'IT'=>array('name'=>'ITALY','code'=>'39'),
        'JM'=>array('name'=>'JAMAICA','code'=>'1876'),
        'JO'=>array('name'=>'JORDAN','code'=>'962'),
        'JP'=>array('name'=>'JAPAN','code'=>'81'),
        'KE'=>array('name'=>'KENYA','code'=>'254'),
        'KG'=>array('name'=>'KYRGYZSTAN','code'=>'996'),
        'KH'=>array('name'=>'CAMBODIA','code'=>'855'),
        'KI'=>array('name'=>'KIRIBATI','code'=>'686'),
        'KM'=>array('name'=>'COMOROS','code'=>'269'),
        'KN'=>array('name'=>'SAINT KITTS AND NEVIS','code'=>'1869'),
        'KP'=>array('name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'850'),
        'KR'=>array('name'=>'KOREA REPUBLIC OF','code'=>'82'),
        'KW'=>array('name'=>'KUWAIT','code'=>'965'),
        'KY'=>array('name'=>'CAYMAN ISLANDS','code'=>'1345'),
        'KZ'=>array('name'=>'KAZAKSTAN','code'=>'7'),
        'LA'=>array('name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'856'),
        'LB'=>array('name'=>'LEBANON','code'=>'961'),
        'LC'=>array('name'=>'SAINT LUCIA','code'=>'1758'),
        'LI'=>array('name'=>'LIECHTENSTEIN','code'=>'423'),
        'LK'=>array('name'=>'SRI LANKA','code'=>'94'),
        'LR'=>array('name'=>'LIBERIA','code'=>'231'),
        'LS'=>array('name'=>'LESOTHO','code'=>'266'),
        'LT'=>array('name'=>'LITHUANIA','code'=>'370'),
        'LU'=>array('name'=>'LUXEMBOURG','code'=>'352'),
        'LV'=>array('name'=>'LATVIA','code'=>'371'),
        'LY'=>array('name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'),
        'MA'=>array('name'=>'MOROCCO','code'=>'212'),
        'MC'=>array('name'=>'MONACO','code'=>'377'),
        'MD'=>array('name'=>'MOLDOVA, REPUBLIC OF','code'=>'373'),
        'ME'=>array('name'=>'MONTENEGRO','code'=>'382'),
        'MF'=>array('name'=>'SAINT MARTIN','code'=>'1599'),
        'MG'=>array('name'=>'MADAGASCAR','code'=>'261'),
        'MH'=>array('name'=>'MARSHALL ISLANDS','code'=>'692'),
        'MK'=>array('name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'389'),
        'ML'=>array('name'=>'MALI','code'=>'223'),
        'MM'=>array('name'=>'MYANMAR','code'=>'95'),
        'MN'=>array('name'=>'MONGOLIA','code'=>'976'),
        'MO'=>array('name'=>'MACAU','code'=>'853'),
        'MP'=>array('name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'),
        'MR'=>array('name'=>'MAURITANIA','code'=>'222'),
        'MS'=>array('name'=>'MONTSERRAT','code'=>'1664'),
        'MT'=>array('name'=>'MALTA','code'=>'356'),
        'MU'=>array('name'=>'MAURITIUS','code'=>'230'),
        'MV'=>array('name'=>'MALDIVES','code'=>'960'),
        'MW'=>array('name'=>'MALAWI','code'=>'265'),
        'MX'=>array('name'=>'MEXICO','code'=>'52'),
        'MY'=>array('name'=>'MALAYSIA','code'=>'60'),
        'MZ'=>array('name'=>'MOZAMBIQUE','code'=>'258'),
        'NA'=>array('name'=>'NAMIBIA','code'=>'264'),
        'NC'=>array('name'=>'NEW CALEDONIA','code'=>'687'),
        'NE'=>array('name'=>'NIGER','code'=>'227'),
        'NG'=>array('name'=>'NIGERIA','code'=>'234'),
        'NI'=>array('name'=>'NICARAGUA','code'=>'505'),
        'NL'=>array('name'=>'NETHERLANDS','code'=>'31'),
        'NO'=>array('name'=>'NORWAY','code'=>'47'),
        'NP'=>array('name'=>'NEPAL','code'=>'977'),
        'NR'=>array('name'=>'NAURU','code'=>'674'),
        'NU'=>array('name'=>'NIUE','code'=>'683'),
        'NZ'=>array('name'=>'NEW ZEALAND','code'=>'64'),
        'OM'=>array('name'=>'OMAN','code'=>'968'),
        'PA'=>array('name'=>'PANAMA','code'=>'507'),
        'PE'=>array('name'=>'PERU','code'=>'51'),
        'PF'=>array('name'=>'FRENCH POLYNESIA','code'=>'689'),
        'PG'=>array('name'=>'PAPUA NEW GUINEA','code'=>'675'),
        'PH'=>array('name'=>'PHILIPPINES','code'=>'63'),
        'PK'=>array('name'=>'PAKISTAN','code'=>'92'),
        'PL'=>array('name'=>'POLAND','code'=>'48'),
        'PM'=>array('name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'),
        'PN'=>array('name'=>'PITCAIRN','code'=>'870'),
        'PR'=>array('name'=>'PUERTO RICO','code'=>'1'),
        'PT'=>array('name'=>'PORTUGAL','code'=>'351'),
        'PW'=>array('name'=>'PALAU','code'=>'680'),
        'PY'=>array('name'=>'PARAGUAY','code'=>'595'),
        'QA'=>array('name'=>'QATAR','code'=>'974'),
        'RO'=>array('name'=>'ROMANIA','code'=>'40'),
        'RS'=>array('name'=>'SERBIA','code'=>'381'),
        'RU'=>array('name'=>'RUSSIAN FEDERATION','code'=>'7'),
        'RW'=>array('name'=>'RWANDA','code'=>'250'),
        'SA'=>array('name'=>'SAUDI ARABIA','code'=>'966'),
        'SB'=>array('name'=>'SOLOMON ISLANDS','code'=>'677'),
        'SC'=>array('name'=>'SEYCHELLES','code'=>'248'),
        'SD'=>array('name'=>'SUDAN','code'=>'249'),
        'SE'=>array('name'=>'SWEDEN','code'=>'46'),
        'SG'=>array('name'=>'SINGAPORE','code'=>'65'),
        'SH'=>array('name'=>'SAINT HELENA','code'=>'290'),
        'SI'=>array('name'=>'SLOVENIA','code'=>'386'),
        'SK'=>array('name'=>'SLOVAKIA','code'=>'421'),
        'SL'=>array('name'=>'SIERRA LEONE','code'=>'232'),
        'SM'=>array('name'=>'SAN MARINO','code'=>'378'),
        'SN'=>array('name'=>'SENEGAL','code'=>'221'),
        'SO'=>array('name'=>'SOMALIA','code'=>'252'),
        'SR'=>array('name'=>'SURINAME','code'=>'597'),
        'ST'=>array('name'=>'SAO TOME AND PRINCIPE','code'=>'239'),
        'SV'=>array('name'=>'EL SALVADOR','code'=>'503'),
        'SY'=>array('name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'),
        'SZ'=>array('name'=>'SWAZILAND','code'=>'268'),
        'TC'=>array('name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'),
        'TD'=>array('name'=>'CHAD','code'=>'235'),
        'TG'=>array('name'=>'TOGO','code'=>'228'),
        'TH'=>array('name'=>'THAILAND','code'=>'66'),
        'TJ'=>array('name'=>'TAJIKISTAN','code'=>'992'),
        'TK'=>array('name'=>'TOKELAU','code'=>'690'),
        'TL'=>array('name'=>'TIMOR-LESTE','code'=>'670'),
        'TM'=>array('name'=>'TURKMENISTAN','code'=>'993'),
        'TN'=>array('name'=>'TUNISIA','code'=>'216'),
        'TO'=>array('name'=>'TONGA','code'=>'676'),
        'TR'=>array('name'=>'TURKEY','code'=>'90'),
        'TT'=>array('name'=>'TRINIDAD AND TOBAGO','code'=>'1868'),
        'TV'=>array('name'=>'TUVALU','code'=>'688'),
        'TW'=>array('name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'886'),
        'TZ'=>array('name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'255'),
        'UA'=>array('name'=>'UKRAINE','code'=>'380'),
        'UG'=>array('name'=>'UGANDA','code'=>'256'),
        'US'=>array('name'=>'UNITED STATES','code'=>'1'),
        'UY'=>array('name'=>'URUGUAY','code'=>'598'),
        'UZ'=>array('name'=>'UZBEKISTAN','code'=>'998'),
        'VA'=>array('name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'),
        'VC'=>array('name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'),
        'VE'=>array('name'=>'VENEZUELA','code'=>'58'),
        'VG'=>array('name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'),
        'VI'=>array('name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'),
        'VN'=>array('name'=>'VIET NAM','code'=>'84'),
        'VU'=>array('name'=>'VANUATU','code'=>'678'),
        'WF'=>array('name'=>'WALLIS AND FUTUNA','code'=>'681'),
        'WS'=>array('name'=>'SAMOA','code'=>'685'),
        'XK'=>array('name'=>'KOSOVO','code'=>'381'),
        'YE'=>array('name'=>'YEMEN','code'=>'967'),
        'YT'=>array('name'=>'MAYOTTE','code'=>'262'),
        'ZA'=>array('name'=>'SOUTH AFRICA','code'=>'27'),
        'ZM'=>array('name'=>'ZAMBIA','code'=>'260'),
        'ZW'=>array('name'=>'ZIMBABWE','code'=>'263')
    );

    public $relArray=array (
        'ANDORRA' => '376',
        'UNITED ARAB EMIRATES' => '971',
        'AFGHANISTAN' => '93',
        'ANTIGUA AND BARBUDA' => '1268',
        'ANGUILLA' => '1264',
        'ALBANIA' => '355',
        'ARMENIA' => '374',
        'NETHERLANDS ANTILLES' => '599',
        'ANGOLA' => '244',
        'ANTARCTICA' => '672',
        'ARGENTINA' => '54',
        'AMERICAN SAMOA' => '1684',
        'AUSTRIA' => '43',
        'AUSTRALIA' => '61',
        'ARUBA' => '297',
        'AZERBAIJAN' => '994',
        'BOSNIA AND HERZEGOVINA' => '387',
        'BARBADOS' => '1246',
        'BANGLADESH' => '880',
        'BELGIUM' => '32',
        'BURKINA FASO' => '226',
        'BULGARIA' => '359',
        'BAHRAIN' => '973',
        'BURUNDI' => '257',
        'BENIN' => '229',
        'SAINT BARTHELEMY' => '590',
        'BERMUDA' => '1441',
        'BRUNEI DARUSSALAM' => '673',
        'BOLIVIA' => '591',
        'BRAZIL' => '55',
        'BAHAMAS' => '1242',
        'BHUTAN' => '975',
        'BOTSWANA' => '267',
        'BELARUS' => '375',
        'BELIZE' => '501',
        'CANADA' => '1',
        'COCOS (KEELING) ISLANDS' => '61',
        'CONGO, THE DEMOCRATIC REPUBLIC OF THE' => '243',
        'CENTRAL AFRICAN REPUBLIC' => '236',
        'CONGO' => '242',
        'SWITZERLAND' => '41',
        'COTE D IVOIRE' => '225',
        'COOK ISLANDS' => '682',
        'CHILE' => '56',
        'CAMEROON' => '237',
        'CHINA' => '86',
        'COLOMBIA' => '57',
        'COSTA RICA' => '506',
        'CUBA' => '53',
        'CAPE VERDE' => '238',
        'CHRISTMAS ISLAND' => '61',
        'CYPRUS' => '357',
        'CZECH REPUBLIC' => '420',
        'GERMANY' => '49',
        'DJIBOUTI' => '253',
        'DENMARK' => '45',
        'DOMINICA' => '1767',
        'DOMINICAN REPUBLIC' => '1809',
        'ALGERIA' => '213',
        'ECUADOR' => '593',
        'ESTONIA' => '372',
        'EGYPT' => '20',
        'ERITREA' => '291',
        'SPAIN' => '34',
        'ETHIOPIA' => '251',
        'FINLAND' => '358',
        'FIJI' => '679',
        'FALKLAND ISLANDS (MALVINAS)' => '500',
        'MICRONESIA, FEDERATED STATES OF' => '691',
        'FAROE ISLANDS' => '298',
        'FRANCE' => '33',
        'GABON' => '241',
        'UNITED KINGDOM' => '44',
        'GRENADA' => '1473',
        'GEORGIA' => '995',
        'GHANA' => '233',
        'GIBRALTAR' => '350',
        'GREENLAND' => '299',
        'GAMBIA' => '220',
        'GUINEA' => '224',
        'EQUATORIAL GUINEA' => '240',
        'GREECE' => '30',
        'GUATEMALA' => '502',
        'GUAM' => '1671',
        'GUINEA-BISSAU' => '245',
        'GUYANA' => '592',
        'HONG KONG' => '852',
        'HONDURAS' => '504',
        'CROATIA' => '385',
        'HAITI' => '509',
        'HUNGARY' => '36',
        'INDONESIA' => '62',
        'IRELAND' => '353',
        'ISRAEL' => '972',
        'ISLE OF MAN' => '44',
        'INDIA' => '91',
        'IRAQ' => '964',
        'IRAN, ISLAMIC REPUBLIC OF' => '98',
        'ICELAND' => '354',
        'ITALY' => '39',
        'JAMAICA' => '1876',
        'JORDAN' => '962',
        'JAPAN' => '81',
        'KENYA' => '254',
        'KYRGYZSTAN' => '996',
        'CAMBODIA' => '855',
        'KIRIBATI' => '686',
        'COMOROS' => '269',
        'SAINT KITTS AND NEVIS' => '1869',
        'KOREA DEMOCRATIC PEOPLES REPUBLIC OF' => '850',
        'KOREA REPUBLIC OF' => '82',
        'KUWAIT' => '965',
        'CAYMAN ISLANDS' => '1345',
        'KAZAKSTAN' => '7',
        'LAO PEOPLES DEMOCRATIC REPUBLIC' => '856',
        'LEBANON' => '961',
        'SAINT LUCIA' => '1758',
        'LIECHTENSTEIN' => '423',
        'SRI LANKA' => '94',
        'LIBERIA' => '231',
        'LESOTHO' => '266',
        'LITHUANIA' => '370',
        'LUXEMBOURG' => '352',
        'LATVIA' => '371',
        'LIBYAN ARAB JAMAHIRIYA' => '218',
        'MOROCCO' => '212',
        'MONACO' => '377',
        'MOLDOVA, REPUBLIC OF' => '373',
        'MONTENEGRO' => '382',
        'SAINT MARTIN' => '1599',
        'MADAGASCAR' => '261',
        'MARSHALL ISLANDS' => '692',
        'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' => '389',
        'MALI' => '223',
        'MYANMAR' => '95',
        'MONGOLIA' => '976',
        'MACAU' => '853',
        'NORTHERN MARIANA ISLANDS' => '1670',
        'MAURITANIA' => '222',
        'MONTSERRAT' => '1664',
        'MALTA' => '356',
        'MAURITIUS' => '230',
        'MALDIVES' => '960',
        'MALAWI' => '265',
        'MEXICO' => '52',
        'MALAYSIA' => '60',
        'MOZAMBIQUE' => '258',
        'NAMIBIA' => '264',
        'NEW CALEDONIA' => '687',
        'NIGER' => '227',
        'NIGERIA' => '234',
        'NICARAGUA' => '505',
        'NETHERLANDS' => '31',
        'NORWAY' => '47',
        'NEPAL' => '977',
        'NAURU' => '674',
        'NIUE' => '683',
        'NEW ZEALAND' => '64',
        'OMAN' => '968',
        'PANAMA' => '507',
        'PERU' => '51',
        'FRENCH POLYNESIA' => '689',
        'PAPUA NEW GUINEA' => '675',
        'PHILIPPINES' => '63',
        'PAKISTAN' => '92',
        'POLAND' => '48',
        'SAINT PIERRE AND MIQUELON' => '508',
        'PITCAIRN' => '870',
        'PUERTO RICO' => '1',
        'PORTUGAL' => '351',
        'PALAU' => '680',
        'PARAGUAY' => '595',
        'QATAR' => '974',
        'ROMANIA' => '40',
        'SERBIA' => '381',
        'RUSSIAN FEDERATION' => '7',
        'RWANDA' => '250',
        'SAUDI ARABIA' => '966',
        'SOLOMON ISLANDS' => '677',
        'SEYCHELLES' => '248',
        'SUDAN' => '249',
        'SWEDEN' => '46',
        'SINGAPORE' => '65',
        'SAINT HELENA' => '290',
        'SLOVENIA' => '386',
        'SLOVAKIA' => '421',
        'SIERRA LEONE' => '232',
        'SAN MARINO' => '378',
        'SENEGAL' => '221',
        'SOMALIA' => '252',
        'SURINAME' => '597',
        'SAO TOME AND PRINCIPE' => '239',
        'EL SALVADOR' => '503',
        'SYRIAN ARAB REPUBLIC' => '963',
        'SWAZILAND' => '268',
        'TURKS AND CAICOS ISLANDS' => '1649',
        'CHAD' => '235',
        'TOGO' => '228',
        'THAILAND' => '66',
        'TAJIKISTAN' => '992',
        'TOKELAU' => '690',
        'TIMOR-LESTE' => '670',
        'TURKMENISTAN' => '993',
        'TUNISIA' => '216',
        'TONGA' => '676',
        'TURKEY' => '90',
        'TRINIDAD AND TOBAGO' => '1868',
        'TUVALU' => '688',
        'TAIWAN, PROVINCE OF CHINA' => '886',
        'TANZANIA, UNITED REPUBLIC OF' => '255',
        'UKRAINE' => '380',
        'UGANDA' => '256',
        'UNITED STATES' => '1',
        'URUGUAY' => '598',
        'UZBEKISTAN' => '998',
        'HOLY SEE (VATICAN CITY STATE)' => '39',
        'SAINT VINCENT AND THE GRENADINES' => '1784',
        'VENEZUELA' => '58',
        'VIRGIN ISLANDS, BRITISH' => '1284',
        'VIRGIN ISLANDS, U.S.' => '1340',
        'VIET NAM' => '84',
        'VANUATU' => '678',
        'WALLIS AND FUTUNA' => '681',
        'SAMOA' => '685',
        'KOSOVO' => '381',
        'YEMEN' => '967',
        'MAYOTTE' => '262',
        'SOUTH AFRICA' => '27',
        'ZAMBIA' => '260',
        'ZIMBABWE' => '263',
    );

    public function getCode($countryName) {
        if (array_key_exists(strtoupper($countryName),$this->relArray)!=false) {
            return $this->relArray[strtoupper($countryName)];
        }
        else {
            return "$countryName cannot determine phone code";
        }
    }


}